import type { CSSProperties } from 'react'

export const assistantBiPageStyles: Record<string, CSSProperties> = {
  page: { minHeight: '100vh', background: '#F2F6FB', color: '#172033', padding: 20, fontFamily: 'Arial, sans-serif' },
  topBar: { display: 'flex', justifyContent: 'space-between', gap: 20, alignItems: 'center', background: 'linear-gradient(135deg,#0F2744,#174A7E)', color: 'white', borderRadius: 18, padding: '22px 26px', boxShadow: '0 16px 40px rgba(15,39,68,.18)' },
  eyebrow: { fontSize: 11, letterSpacing: 1.5, fontWeight: 900, opacity: .75 },
  title: { margin: '5px 0 4px', fontSize: 30 },
  subtitle: { margin: 0, opacity: .86, fontSize: 14 },
  topActions: { display: 'flex', gap: 9, flexWrap: 'wrap', justifyContent: 'flex-end' },
  primaryButton: { border: 0, borderRadius: 10, padding: '11px 16px', background: '#16A34A', color: 'white', fontWeight: 900, cursor: 'pointer', display: 'inline-flex', alignItems: 'center' },
  secondaryButton: { border: '1px solid rgba(255,255,255,.35)', borderRadius: 10, padding: '11px 16px', background: 'rgba(255,255,255,.08)', color: 'white', fontWeight: 800, cursor: 'pointer' },
  templateSection: { marginTop: 16, background: 'white', border: '1px solid #DCE5F0', borderRadius: 15, padding: 16 },
  sectionHeading: { display: 'flex', justifyContent: 'space-between', gap: 12, alignItems: 'center' },
  sectionTitle: { margin: 0, fontSize: 18 },
  sectionText: { margin: '4px 0 0', color: '#64748B', fontSize: 12 },
  proBadge: { background: '#DCFCE7', color: '#15803D', border: '1px solid #BBF7D0', borderRadius: 999, padding: '5px 9px', fontSize: 10, fontWeight: 900, letterSpacing: .6 },
  templateGrid: { display: 'grid', gridTemplateColumns: 'repeat(auto-fit,minmax(210px,1fr))', gap: 9, marginTop: 12 },
  templateCard: { textAlign: 'left', border: '1px solid #DCE5F0', borderRadius: 11, padding: 12, background: '#F8FAFC', cursor: 'pointer', display: 'grid', gap: 4, color: '#172033' },
  workspace: { display: 'grid', gridTemplateColumns: 'minmax(410px,.85fr) minmax(600px,1.65fr)', gap: 16, alignItems: 'start', marginTop: 16 },
  builder: { background: 'white', border: '1px solid #DCE5F0', borderRadius: 15, padding: 16, position: 'sticky', top: 88, maxHeight: 'calc(100vh - 105px)', overflowY: 'auto', boxShadow: '0 8px 24px rgba(15,23,42,.05)' },
  results: { minWidth: 0 },
  step: { paddingBottom: 16, marginBottom: 16, borderBottom: '1px solid #E8EEF5' },
  stepTitle: { display: 'flex', gap: 8, alignItems: 'center', marginBottom: 10 },
  stepNumber: { width: 23, height: 23, borderRadius: '50%', background: '#2563EB', color: 'white', display: 'inline-flex', alignItems: 'center', justifyContent: 'center', fontSize: 11, fontWeight: 900 },
  choiceGrid: { display: 'grid', gridTemplateColumns: 'repeat(2,minmax(0,1fr))', gap: 7 },
  choice: { textAlign: 'left', border: '1px solid #DCE5F0', borderRadius: 9, padding: 9, background: '#FFF', cursor: 'pointer', display: 'grid', gap: 4, color: '#172033', fontSize: 12 },
  choiceCompact: { minHeight: 62 },
  choiceActive: { border: '2px solid #2563EB', background: '#EFF6FF', padding: 8 },
  subjectImpact: { marginTop: 9, padding: 10, borderRadius: 9, background: '#F1F5F9', color: '#475569', display: 'grid', gap: 4, fontSize: 11, lineHeight: 1.4 },
  chipRow: { display: 'flex', gap: 6, flexWrap: 'wrap' },
  chip: { border: '1px solid #CBD5E1', borderRadius: 999, background: 'white', padding: '6px 10px', cursor: 'pointer', fontSize: 11, color: '#334155' },
  chipActive: { background: '#1D4ED8', borderColor: '#1D4ED8', color: 'white', fontWeight: 800 },
  orderHint: { color: '#64748B', fontSize: 10, marginBottom: 7 },
  selectedPath: { display: 'flex', flexWrap: 'wrap', gap: 5, padding: 8, marginBottom: 8, background: '#F8FAFC', borderRadius: 8, color: '#64748B', fontSize: 10 },
  pathPill: { background: '#DBEAFE', color: '#1D4ED8', borderRadius: 999, padding: '4px 7px', fontWeight: 800 },
  dateRow: { display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 8, marginBottom: 9 },
  fieldLabel: { display: 'grid', gap: 4, fontSize: 11, color: '#475569', fontWeight: 800 },
  input: { border: '1px solid #CBD5E1', borderRadius: 8, padding: 8, background: 'white' },
  visualGrid: { display: 'grid', gridTemplateColumns: 'repeat(2,minmax(0,1fr))', gap: 7 },
  textarea: { width: '100%', minHeight: 76, resize: 'vertical', border: '1px solid #CBD5E1', borderRadius: 9, padding: 9, boxSizing: 'border-box', fontFamily: 'inherit' },
  freeTextHint: { marginTop: 7, padding: 8, background: '#EFF6FF', color: '#1D4ED8', borderRadius: 8, fontSize: 10, lineHeight: 1.4 },
  previewBox: { marginTop: 8, background: '#F8FAFC', borderRadius: 8, padding: 8, fontSize: 11 },
  previewText: { whiteSpace: 'pre-wrap', fontFamily: 'inherit', color: '#475569', lineHeight: 1.45 },
  confirmCard: { border: '1px solid #93C5FD', background: '#EFF6FF', borderRadius: 12, padding: 12, display: 'grid', gap: 10 },
  planLine: { display: 'grid', gridTemplateColumns: '120px 1fr', gap: 9, alignItems: 'start', fontSize: 11, color: '#334155' },
  interpretationBox: { display: 'grid', gap: 5, padding: 10, border: '1px solid #86EFAC', borderRadius: 9, background: '#F0FDF4', color: '#166534', fontSize: 11, lineHeight: 1.45 },
  assumptionList: { margin: '2px 0 0 18px', padding: 0 },
  clarificationBox: { border: '1px solid #F59E0B', background: '#FFFBEB', color: '#92400E', borderRadius: 8, padding: 9, fontSize: 10, lineHeight: 1.45 },
  settingBlock: { display: 'flex', justifyContent: 'space-between', alignItems: 'center', gap: 10, borderTop: '1px solid #BFDBFE', paddingTop: 9, fontSize: 11 },
  toggleRow: { display: 'flex', gap: 5 },
  toggleButton: { border: '1px solid #94A3B8', borderRadius: 7, background: 'white', color: '#475569', fontWeight: 800, padding: '5px 9px', cursor: 'pointer' },
  toggleActive: { background: '#1D4ED8', color: 'white', borderColor: '#1D4ED8' },
  selectLabel: { display: 'grid', gap: 5, color: '#334155', fontSize: 11, fontWeight: 800 },
  select: { border: '1px solid #93C5FD', borderRadius: 8, padding: 8, background: 'white', color: '#172033' },
  warningBox: { border: '1px solid #F59E0B', background: '#FFFBEB', color: '#92400E', borderRadius: 8, padding: 9, fontSize: 10, lineHeight: 1.45 },
  confirmActions: { display: 'grid', gridTemplateColumns: '1fr 1.4fr', gap: 8, marginTop: 2 },
  cancelButton: { border: '1px solid #CBD5E1', borderRadius: 9, background: 'white', color: '#475569', fontWeight: 800, padding: 10, cursor: 'pointer' },
  confirmButton: { border: 0, borderRadius: 9, background: '#16A34A', color: 'white', fontWeight: 900, padding: 10, cursor: 'pointer' },
  error: { marginBottom: 10, borderRadius: 9, padding: 10, background: '#FEF2F2', color: '#B91C1C', border: '1px solid #FECACA', fontSize: 12, whiteSpace: 'pre-wrap' },
  emptyState: { minHeight: 620, background: 'white', border: '1px dashed #B8C7D9', borderRadius: 16, display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', color: '#64748B', textAlign: 'center', padding: 30 },
  emptyIcon: { width: 72, height: 72, borderRadius: 22, background: '#DBEAFE', color: '#1D4ED8', display: 'flex', alignItems: 'center', justifyContent: 'center', fontWeight: 900, fontSize: 24 },
  emptyFeatures: { display: 'flex', flexWrap: 'wrap', gap: 8, marginTop: 14, justifyContent: 'center' },
}
