import { NextRequest, NextResponse } from 'next/server'
import { createClient } from '@supabase/supabase-js'

export const runtime = 'nodejs'
export const dynamic = 'force-dynamic'

const MODEL = process.env.OPENAI_MODEL || 'gpt-4.1-mini'
const SUMMARY_SAMPLE_ROWS = 200
const SCHEMA: Record<string, string[]> = {
  indicateur_factures_mensuel: ['annee','mois','collaborateur_facture','collaborateur_tiers','agence_collaborateur','depot','departement_tiers','numero_tiers','intitule_tiers','famille','famille_macro','hors_statistique','nb_lignes','quantite','ca_ht','marge_valeur'],
  indicateur_activite_mensuel: ['annee','mois','type_document','collaborateur_facture','collaborateur_tiers','agence_collaborateur','depot','departement_tiers','numero_tiers','intitule_tiers','famille','famille_macro','hors_statistique','nb_lignes','quantite','ca_ht','marge_valeur'],
  indicateur_devis_mensuel: ['annee','mois','collaborateur_facture','collaborateur_tiers','agence_collaborateur','depot','departement_tiers','numero_tiers','intitule_tiers','famille','famille_macro','nb_lignes','quantite','ca_ht','marge_valeur'],
  indicateur_flux_articles_mensuel: ['annee','mois','flux','type_document','depot','collaborateur_tiers','famille_macro','famille','reference_article','designation','hors_statistique','nb_lignes','quantite','ca_ht','marge_valeur'],
  facture_lignes: ['type_document','numero_piece','date_facture','date_bl','numero_tiers_entete','intitule_tiers_entete','reference_article','designation','quantite','montant_ht','marge_valeur','collaborateur','depot'],
  devis_lignes: ['type_document','numero_piece','date_devis','numero_tiers_entete','intitule_tiers_entete','reference_article','designation','quantite','montant_ht','marge_valeur','collaborateur','depot'],
  activite_lignes: ['type_document','numero_piece','date_piece','date_bl','numero_tiers_entete','intitule_tiers_entete','reference_article','designation','quantite','montant_ht','marge_valeur','collaborateur','depot'],
  ref_tiers: ['numero','intitule','code_postal','representant'],
  ref_collaborateurs: ['nom','agence'],
  ref_articles: ['reference_article','designation','famille','hors_statistique'],
  ref_familles: ['famille','famille_macro'],
}
const ALLOWED = new Set(Object.keys(SCHEMA))
const REFERENCE_JOINS = new Set(['ref_tiers','ref_collaborateurs','ref_articles','ref_familles'])
type J = Record<string, any>
type Row = Record<string, unknown>
type Result = { rows: Row[]; sql: string; repaired: boolean; reason: string; visualization: J | null }

const json = (value: Record<string, unknown>, status = 200) => NextResponse.json(value, { status })
function env(name: string) { const value = process.env[name]; if (!value) throw new Error(`Variable d'environnement manquante : ${name}`); return value }
function client() { return createClient(env('NEXT_PUBLIC_SUPABASE_URL'), env('SUPABASE_SERVICE_ROLE_KEY'), { auth: { persistSession: false, autoRefreshToken: false } }) }
function toRows(value: unknown): Row[] { return Array.isArray(value) ? value.filter((v): v is Row => !!v && typeof v === 'object' && !Array.isArray(v)) : value && typeof value === 'object' ? [value as Row] : [] }
async function execute(sql: string) { const { data, error } = await client().rpc('atelier_ai_run_readonly_sql', { p_sql: sql }); if (error) throw new Error(error.message); return toRows(data) }
function parse(text: string): J { const s=String(text||'').trim(); try{return JSON.parse(s)}catch{} const f=s.match(/```(?:json)?\s*([\s\S]*?)```/i)?.[1]; if(f)return JSON.parse(f.trim()); const a=s.indexOf('{'),b=s.lastIndexOf('}'); if(a>=0&&b>a)return JSON.parse(s.slice(a,b+1)); throw new Error('Réponse IA non JSON.') }
async function openAi(messages: Array<{role:'system'|'user';content:string}>) { const r=await fetch('https://api.openai.com/v1/chat/completions',{method:'POST',headers:{Authorization:`Bearer ${env('OPENAI_API_KEY')}`,'Content-Type':'application/json'},body:JSON.stringify({model:MODEL,temperature:.03,response_format:{type:'json_object'},messages})}); const p=await r.json().catch(()=>({})) as J; if(!r.ok)throw new Error(p?.error?.message||`Erreur OpenAI ${r.status}`); return parse(p?.choices?.[0]?.message?.content||'{}') }
function clean(value: string) { return String(value||'').trim().replace(/^```sql\s*/i,'').replace(/^```\s*/i,'').replace(/```$/i,'').replace(/;\s*$/,'').trim() }
function removeResultLimits(sql: string) { return sql.replace(/\s+limit\s+\d+(?:\s+offset\s+\d+)?/gi, '').replace(/\s+fetch\s+(?:first|next)\s+\d+\s+rows?\s+only/gi, '').trim() }
function validate(value: string) { let sql=removeResultLimits(clean(value)); if(!/^\s*(select|with)\b/i.test(sql))throw new Error('SQL SELECT attendu.'); if(/;|--|\/\*/.test(sql)||/\b(insert|update|delete|drop|alter|truncate|create|grant|revoke|copy|call|do|execute|merge|vacuum|refresh)\b/i.test(sql))throw new Error('Instruction SQL non autorisée.'); const ctes=new Set([...sql.matchAll(/(?:\bwith\b|,)\s*([a-z_][a-z0-9_]*)\s+as\s*\(/gi)].map((m)=>m[1].toLowerCase())); const refs=[...sql.matchAll(/\b(from|join)\s+((?:public\.)?[a-zA-Z_][a-zA-Z0-9_]*)/gi)]; for(const ref of refs){const keyword=ref[1].toLowerCase(),table=ref[2].replace(/^public\./i,'').toLowerCase(); if(!ALLOWED.has(table)&&!ctes.has(table))throw new Error(`Table non autorisée : ${table}`); if(keyword==='join'&&ALLOWED.has(table)&&!REFERENCE_JOINS.has(table))throw new Error(`JOIN non autorisé vers ${table}.`)} return sql }
const q=(v:unknown)=>`'${String(v??'').replaceAll("'","''")}'`
function inSql(column:string,values:unknown[]){const list=values.map(String).map((v)=>v.trim()).filter(Boolean);return list.length?`${column} IN (${list.map(q).join(', ')})`:''}
function monthKey(v:unknown){const m=String(v||'').match(/^(\d{4})-(\d{2})/);if(!m)return null;const n=Number(m[2]);return n>=1&&n<=12?Number(m[1])*100+n:null}
function label(k:string){const d:Record<string,string>={annee:'Année',mois:'Mois',agence_collaborateur:'Agence',depot:'Dépôt',collaborateur_facture:'Collaborateur du document',collaborateur_tiers:'Collaborateur du client',departement_tiers:'Département client',famille_macro:'Famille macro',famille:'Famille',type_document:'Type document',numero_tiers:'Code client',intitule_tiers:'Client',reference_article:'Référence article',designation:'Désignation',ca_ht:'CA HT',marge_valeur:'Marge €',marge_pct:'Marge %',quantite:'Quantité',nb_lignes:'Nb lignes',panier_moyen:'Panier moyen'};return d[k]||k.replace(/_/g,' ')}
function metric(k:string,c:string[]){if(k==='ca_ht'&&c.includes(k))return'SUM(ca_ht) AS ca_ht';if(k==='quantite'&&c.includes(k))return'SUM(quantite) AS quantite';if(k==='marge_valeur'&&c.includes(k))return'SUM(marge_valeur) AS marge_valeur';if(k==='nb_lignes'&&c.includes(k))return'SUM(nb_lignes) AS nb_lignes';if(k==='marge_pct'&&c.includes('marge_valeur')&&c.includes('ca_ht'))return'CASE WHEN SUM(ca_ht)<>0 THEN SUM(marge_valeur)/SUM(ca_ht)*100 ELSE 0 END AS marge_pct';return''}
function source(body:J,dims:string[]){const s=String(body?.dataContext?.semanticSubject?.key||'');if(s==='articles'||dims.some((d:string)=>d==='reference_article'||d==='designation'))return'indicateur_flux_articles_mensuel';if(s==='factures')return'indicateur_factures_mensuel';if(s==='devis')return'indicateur_devis_mensuel';if(s==='clients')return'indicateur_factures_mensuel';return'indicateur_activite_mensuel'}
function needsDetailed(dims:string[]){return dims.some((d)=>d==='reference_article'||d==='designation')&&dims.some((d)=>['agence_collaborateur','departement_tiers','numero_tiers','intitule_tiers','collaborateur_facture'].includes(d))}
function detailSource(body:J){const s=String(body?.dataContext?.semanticSubject?.key||'');if(s==='factures'||s==='clients')return{table:'facture_lignes',date:'l.date_facture',types:[] as string[]};if(s==='devis')return{table:'devis_lignes',date:'l.date_devis',types:[] as string[]};if(s==='ventes_bl')return{table:'activite_lignes',date:'COALESCE(l.date_bl,l.date_piece)',types:['BL']};return{table:'activite_lignes',date:'COALESCE(l.date_piece,l.date_bl)',types:[] as string[]}}
function cpDigits(){return"REGEXP_REPLACE(COALESCE(t.code_postal::text,''),'[^0-9]','','g')"}
function deptExpr(){const d=cpDigits();return`CASE WHEN ${d} ~ '^(971|972|973|974|975|976|977|978|984|986|987|988)' THEN LEFT(${d},3) ELSE LEFT(LPAD(${d},5,'0'),2) END`}
function detailDim(k:string,date:string){const dep=deptExpr(),m:Record<string,string>={mois:`EXTRACT(MONTH FROM ${date})::int`,annee:`EXTRACT(YEAR FROM ${date})::int`,agence_collaborateur:"COALESCE(NULLIF(BTRIM(c.agence::text),''),'NON RENSEIGNE')",depot:"COALESCE(NULLIF(BTRIM(l.depot::text),''),'NON RENSEIGNE')",collaborateur_facture:"COALESCE(NULLIF(BTRIM(l.collaborateur::text),''),'NON RENSEIGNE')",collaborateur_tiers:"COALESCE(NULLIF(BTRIM(t.representant::text),''),'NON RENSEIGNE')",departement_tiers:`COALESCE(NULLIF(${dep},''),'NON RENSEIGNE')`,famille_macro:"COALESCE(NULLIF(BTRIM(f.famille_macro::text),''),'NON RENSEIGNE')",famille:"COALESCE(NULLIF(BTRIM(a.famille::text),''),'NON RENSEIGNE')",numero_tiers:"COALESCE(NULLIF(BTRIM(l.numero_tiers_entete::text),''),'NON RENSEIGNE')",intitule_tiers:"COALESCE(NULLIF(BTRIM(l.intitule_tiers_entete::text),''),'NON RENSEIGNE')",reference_article:"COALESCE(NULLIF(BTRIM(l.reference_article::text),''),'NON RENSEIGNE')",designation:"COALESCE(NULLIF(BTRIM(l.designation::text),''),'NON RENSEIGNE')",type_document:"COALESCE(NULLIF(BTRIM(l.type_document::text),''),'NON RENSEIGNE')"};if(!m[k])throw new Error(`${label(k)} n'est pas disponible dans l'extraction détaillée.`);return m[k]}
function detailMetric(k:string){if(k==='ca_ht')return'SUM(l.montant_ht) AS ca_ht';if(k==='quantite')return'SUM(l.quantite) AS quantite';if(k==='marge_valeur')return'SUM(l.marge_valeur) AS marge_valeur';if(k==='nb_lignes')return'COUNT(*) AS nb_lignes';if(k==='panier_moyen')return'CASE WHEN COUNT(DISTINCT l.numero_piece)<>0 THEN SUM(l.montant_ht)/COUNT(DISTINCT l.numero_piece) ELSE 0 END AS panier_moyen';if(k==='marge_pct')return'CASE WHEN SUM(l.montant_ht)<>0 THEN SUM(l.marge_valeur)/SUM(l.montant_ht)*100 ELSE 0 END AS marge_pct';return''}
function macroFilter(question:string){const p=question.match(/Précision utilisateur\s*:\s*([^\n]+)/i)?.[1]||'';return p.match(/famille\s+macro\s+(?:est\s+|=\s*|:\s*)?([A-Za-z0-9][A-Za-z0-9/_-]*)/i)?.[1]||''}
function detailed(body:J,question:string,dims:string[],wanted:string[],kind:string):Result{const src=detailSource(body),de=dims.map((key)=>({key,expr:detailDim(key,src.date)})),metrics=wanted.map((key)=>({key,sql:detailMetric(key)})).filter((x)=>!!x.sql);if(!metrics.length)throw new Error('Aucune mesure disponible pour cette extraction.');const f=body?.globalFilters||{},p=body?.dataContext?.activeTemporalContext||{},where:string[]=[];if(p.dateStart)where.push(`${src.date} >= ${q(p.dateStart)}::date`);if(p.dateEnd)where.push(`${src.date} <= ${q(p.dateEnd)}::date`);const requested=Array.isArray(f.typesDocument)?f.typesDocument.map(String).filter(Boolean):[],types=requested.length?requested:src.types;if(types.length){const x=inSql('l.type_document',types);if(x)where.push(x)}const agencies=Array.isArray(f.agences)?f.agences:[];if(agencies.length){const x=inSql("COALESCE(NULLIF(BTRIM(c.agence::text),''),'NON RENSEIGNE')",agencies);if(x)where.push(x)}const collaborators=Array.isArray(f.collaborateursTiers)?f.collaborateursTiers:[];if(collaborators.length){const x=inSql("COALESCE(NULLIF(BTRIM(t.representant::text),''),'NON RENSEIGNE')",collaborators);if(x)where.push(x)}const departments=Array.isArray(f.departementsTiers)?f.departementsTiers:[];if(departments.length){const x=inSql(deptExpr(),departments);if(x)where.push(x)}if(String(f.horsStatistique||'non')==='non')where.push('COALESCE(a.hors_statistique,FALSE)=FALSE');const macro=macroFilter(question);if(macro)where.push(`BTRIM(COALESCE(f.famille_macro::text,''))=${q(macro)}`);const group=de.map((_,i)=>String(i+1)).join(', '),sql=validate(`SELECT\n  ${[...de.map((x)=>`${x.expr} AS ${x.key}`),...metrics.map((x)=>x.sql)].join(',\n  ')}\nFROM public.${src.table} l\nLEFT JOIN public.ref_tiers t ON BTRIM(t.numero::text)=BTRIM(l.numero_tiers_entete::text)\nLEFT JOIN public.ref_collaborateurs c ON BTRIM(c.nom::text)=BTRIM(t.representant::text)\nLEFT JOIN public.ref_articles a ON BTRIM(a.reference_article::text)=BTRIM(l.reference_article::text)\nLEFT JOIN public.ref_familles f ON BTRIM(f.famille::text)=BTRIM(a.famille::text)${where.length?`\nWHERE ${where.join('\n  AND ')}`:''}\nGROUP BY ${group}\nORDER BY ${group}`),keys=metrics.map((x)=>x.key),kinds:Record<string,string>={tableau:'table',courbe:'line',histogramme:'bar',histogramme_empile:'stacked_bar',camembert:'pie'};return{rows:[],sql,repaired:false,reason:`Extraction détaillée depuis ${src.table}, enrichie par les référentiels tiers, collaborateurs, articles et familles.`,visualization:{kind:kinds[kind]||'table',title:`${label(keys[0]||'')} par ${label(dims[0]||'')}${dims[1]?` et ${label(dims[1])}`:''}`,xKey:dims[0],stackBy:dims[1]||undefined,valueKey:keys[0],yKeys:keys,columns:[...dims,...keys]}}}
function aggregate(body:J,dims:string[],wanted:string[],kind:string):Result{const table=source(body,dims),cols=SCHEMA[table]||[],missing=dims.find((d)=>!cols.includes(d));if(missing)throw new Error(`${label(missing)} n'existe pas dans ${table}. Aucune substitution ne sera faite.`);const metrics=wanted.map((key)=>({key,sql:metric(key,cols)})).filter((m)=>!!m.sql);if(!metrics.length)throw new Error('Aucune mesure disponible.');const f=body?.globalFilters||{},where:string[]=[],p=body?.dataContext?.activeTemporalContext||{},a=monthKey(p.dateStart),b=monthKey(p.dateEnd);if(a&&b)where.push(`(annee*100+mois) BETWEEN ${Math.min(a,b)} AND ${Math.max(a,b)}`);if(cols.includes('hors_statistique')&&String(f.horsStatistique||'non')==='non')where.push('hors_statistique=FALSE');for(const x of [{c:'agence_collaborateur',v:Array.isArray(f.agences)?f.agences:[]},{c:'departement_tiers',v:Array.isArray(f.departementsTiers)?f.departementsTiers:[]}]){if(!x.v.length)continue;if(!cols.includes(x.c))throw new Error(`${label(x.c)} est absent de ${table}; aucune autre dimension ne peut le remplacer.`);const cond=inSql(x.c,x.v);if(cond)where.push(cond)}const types=Array.isArray(f.typesDocument)?f.typesDocument:[];if(types.length&&cols.includes('type_document')){const x=inSql('type_document',types);if(x)where.push(x)}const sql=validate(`SELECT\n  ${[...dims,...metrics.map((m)=>m.sql)].join(',\n  ')}\nFROM public.${table}${where.length?`\nWHERE ${where.join('\n  AND ')}`:''}\nGROUP BY ${dims.join(', ')}\nORDER BY ${dims.join(', ')}`),keys=metrics.map((m)=>m.key),kinds:Record<string,string>={tableau:'table',courbe:'line',histogramme:'bar',histogramme_empile:'stacked_bar',camembert:'pie'};return{rows:[],sql,repaired:false,reason:`Requête guidée complète sur ${table}.`,visualization:{kind:kinds[kind]||'table',title:`${label(keys[0]||'')} par ${label(dims[0]||'')}${dims[1]?` et ${label(dims[1])}`:''}`,xKey:dims[0],stackBy:dims[1]||undefined,valueKey:keys[0],yKeys:keys,columns:[...dims,...keys]}}}
function guided(body:J,question:string):Result|null{const r=body?.dataContext?.visualizationRequest;if(!r||typeof r!=='object')return null;const all:string[]=Array.isArray(r.dimensions)?r.dimensions.map(String):[],wanted:string[]=Array.isArray(r.measures)?r.measures.map(String):[];if(!all.length||!wanted.length)return null;const kind=String(r.kind||'tableau'),dims:string[]=kind==='histogramme_empile'?all.slice(0,2):all;return needsDetailed(dims)?detailed(body,question,dims,wanted,kind):aggregate(body,dims,wanted,kind)}
function schemaPrompt(){return Object.entries(SCHEMA).map(([t,c])=>`- ${t}: ${c.join(', ')}`).join('\n')+'\nSELECT complet seulement, sans LIMIT. Les JOIN sont permis uniquement vers les tables ref_*. Ne remplace jamais departement_tiers par depot.'}
async function legacy(question:string,body:J):Promise<Result>{const g=await openAi([{role:'system',content:`Génère du SQL PostgreSQL en JSON. ${schemaPrompt()}`},{role:'user',content:`Question: ${question}\nFiltres: ${JSON.stringify(body?.globalFilters||{})}\nRetourne {"sql":"...","reason":"..."}.`}]);let sql=String(g?.sql||''),reason=String(g?.reason||'SQL IA.'),repaired=false;try{sql=validate(sql);return{rows:await execute(sql),sql,repaired,reason,visualization:null}}catch(e:unknown){const c=await openAi([{role:'system',content:`Corrige le SQL en JSON. ${schemaPrompt()}`},{role:'user',content:`SQL: ${clean(sql)}\nErreur: ${e instanceof Error?e.message:String(e)}\nRetourne {"sql":"...","reason":"..."}.`}]);sql=validate(String(c?.sql||''));reason=String(c?.reason||'SQL corrigé.');repaired=true;return{rows:await execute(sql),sql,repaired,reason,visualization:null}}}
function infer(data:Row[]){const keys=Array.from(new Set(data.slice(0,50).flatMap((r)=>Object.keys(r))));return keys.map((key)=>{const l=key.toLowerCase(),vals=data.slice(0,30).map((r)=>r[key]).filter((v)=>v!==null&&v!==undefined&&v!==''),num=vals.some((v)=>Number.isFinite(Number(String(v).replace(',','.')))),type=l.includes('pct')?'percent':l.includes('ca')||l.includes('marge')||l.includes('panier')?'currency':num?'number':'text';return{key,label:label(key),type}})}
export async function POST(request:NextRequest){try{const body=await request.json().catch(()=>({})) as J,question=String(body?.question||'').trim();if(!question)return json({error:'Question vide.'},400);const structured=guided(body,question),result=structured||await legacy(question,body);if(structured)result.rows=await execute(structured.sql);const summarySample=result.rows.slice(0,SUMMARY_SAMPLE_ROWS);let answer=`Analyse exécutée sur ${result.rows.length} ligne(s).`;try{const s=await openAi([{role:'system',content:'Réponds en français et en JSON strict.'},{role:'user',content:`Question: ${question}\nSQL: ${result.sql}\nNombre total de lignes: ${result.rows.length}\nÉchantillon: ${JSON.stringify(summarySample).slice(0,20000)}\nRetourne {"answer":"synthèse courte"}.`}]);answer=String(s?.answer||answer)}catch{}return json({answer,sql:result.sql,sql_repaired:result.repaired,sql_repair_reason:result.reason,row_count:result.rows.length,rows_preview:result.rows,columns:infer(result.rows),visualization:result.visualization,proposed_widgets:[],is_complete:true,mode:structured?'guided_deterministic_db':'aggregated_db',version:'STEP-9-DETAILED-RELATIONS-01'})}catch(e:unknown){return json({error:e instanceof Error?e.message:String(e)},500)}}
